# 一、 构建node编译容器
FROM harbor.uuzu.com/information/node:10.16-alpine as frontend

# 1. 拷贝代码到node容器
COPY . /app/

# 2. 定义工作目录
WORKDIR /app

# 3. 安装依赖并编译代码到dist目录
RUN npm install --registry=https://registry.npm.taobao.org \
    && npm run build

# 二、 构建运行容器
FROM harbor.uuzu.com/information/nginx:alpine as nginx

# 1. 注入站点配置文件
COPY domain.conf /etc/nginx/conf.d/default.conf

# 2. 从第一步node容器中拷贝编译完成的代码到web根目录
COPY --from=frontend /app/dist/demo /app/